import "./globals.css";

import { Inter } from "next/font/google";
import { Toaster } from "./_components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col items-center justify-center text-pretty bg-slate-100 font-sans antialiased ${inter.variable}`}
      >
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
